name: Sample workflow to run query

on:
  workflow_dispatch:

jobs:
  check_bazel_query:
    name: Attempt to run Bazel query that breaks in CI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.0.0
      - name: Run command
        run: |
          bazel query --noshow_progress --universe_scope=//... --order_output=no "filter('^[^@]', kind(test, allrdeps(siblings(rbuildfiles(WORKSPACE)))))"
